import "./globals.css";
import { Navbar } from "../components/navbar";
import ResponsiveIndicators from "@/components/TailwindIndicator";
import Footer from "./home/footer";
// import { ThemeProvider } from "@/components/ui/theme";

export const metadata = {
  title: "Minimal Web Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ResponsiveIndicators />
        {children}
      </body>
    </html>
  );
}
